feature_spec_version: v1
epoch_sec: 30
channel_aliases:
  ecg:
    - ecg1 ecg2
    - ecg
    - ekg
    - ecg1
    - ecg2
    - x2
    - heart rate varia
  resp:
    - pleth
    - torace
    - thorax
    - addome
    - adddome
    - abdomen
    - abdo
    - flusso
    - flow
    - x3
    - x4
    - x5
    - x6
    - cannula
    - canula
    - termistore
  emg:
    - emg1 emg2
    - emg emg
    - emg1
    - emg2
    - emg
    - chin1
    - chin2
    - chin
    - x1
    - deltoide
  movement:
    - position
    - posizione
    - dx1 dx2
    - sx1 sx2
    - tib dx
    - tib sx
    - tib sin
    - stat
    - roc loc
    - loc
    - roc
    - x7
    - x8
thresholds:
  min_beats_per_epoch: 8
  ecg_sqi_thresh: 0.4
  ecg_rr_min_sec: 0.25
  ecg_rr_max_sec: 2.5
  hr_gap_fill_max_epochs: 2
  hr_median_window: 5
  hr_jump_max_delta: 15.0
  hr_smooth_alpha: 0.3
  hr_smooth_window: 0
  hr_range_bpm: [30, 220]
  rr_range_bpm: [4, 40]
  rr_conf_min: 0.4
  rr_agree_tol: 3.0
  rr_smooth_alpha: 0.4
  rr_gap_fill_max_epochs: 4
  rr_quality_min: 20
  edr_band_hz: [0.1, 0.5]
  edr_fs: 4.0
  min_breaths_per_epoch: 2
  ecg_band_hz: [0.5, 40.0]
  resp_band_hz: [0.1, 0.5]
flags:
  unsupported_fields: true
